# 又拍云配置
[upyun]
service_name = "your-service-name"
operator_name = "your-operator-name"
operator_password = "your-operator-password"
domain = "your-domain"

# WebSocket配置
[websocket]
max_message_size = 104857600  # 100MB in bytes 